#!/bin/bash
END=50
USER=
FORKS=~/.cache/vforks
VPKG_PATH=~/.local/src/ymir/void-packages

if [ -e $FORKS ]; then
	if [ $(stat -c '%w' $FORKS | cut -f1 -d' ') != $(date +"%Y-%m-%d") ]; then
		notify-send "Updating repository list..." "This may take a moment"
		for ((i=1;i<=END;i++)); do
			curl -u ${USER}:${GITHUB_TOKEN} https://api.github.com/repos/void-linux/void-packages/forks?page=$i >> $FORKS
		done
		sed -i 's|\(.*\)}.*|\1|' $FORKS
	fi
else
	for ((i=1;i<=END;i++)); do
		curl -u ${USER}:${GITHUB_TOKEN} https://api.github.com/repos/void-linux/void-packages/forks?page=$i >> $FORKS
	done
	sed -i 's|\(.*\)}.*|\1|' $FORKS
fi

REPO=$(grep "full_name" $FORKS | cut -f2 -d':' | sed 's/\"//g; s/\,//g; s/ //g' | dmenu -p "Select repository:" -l 20)
[ -z $REPO ] && exit
ANS1=$(printf "Yes\\nNo" | dmenu -p "Exit script and explore repository in browser?")
if [ $ANS1 = "Yes" ]; then
	$BROWSER https://github.com/${REPO}
	exit
fi

cd $VPKG_PATH
GUSER=$(echo $REPO | cut -f1 -d'/')
git remote add $GUSER https://github.com/${REPO}.git
git fetch $GUSER
PKG=$(git ls-files --with-tree $GUSER | grep srcpkgs | cut -f2 -d'/' | awk '!x[$0]++' | dmenu -p "Select package:" -l 20)
git cherry-pick -x -m 1 $(git log --all --pretty=oneline ${GUSER}/master -- srcpkgs/${PKG} | head -1)

ANS2=$(printf "Yes\\nNo" | dmenu -p "Build ${PKG}?")
if [ $ANS="Yes" ]; then
	notify-send "Building ${PKG}..." "This will likely take a while"
	./xbps-src pkg $PKG
	cd
else
	cd
	exit
fi
