#!/bin/bash
END=50
USER=
FORKS=~/.cache/vforks
VPKG_PATH=~/.local/src/ymir/void-packages

if [ -e $FORKS ]; then
	if [ $(stat -c '%w' $FORKS | cut -f1 -d' ') != $(date +"%Y-%m-%d") ]; then
		notify-send "Updating repository list..." "This may take a moment"
		for ((i=1;i<=END;i++)); do
			curl -u $USER:$GITHUB_TOKEN https://api.github.com/repos/void-linux/void-packages/forks?page=$i >> $FORKS
		done
		sed -i 's|\(.*\)}.*|\1|' $FORKS
	fi
else
	for ((i=1;i<=END;i++)); do
		curl -u $USER:$GITHUB_TOKEN https://api.github.com/repos/void-linux/void-packages/forks?page=$i >> $FORKS
	done
	sed -i 's|\(.*\)}.*|\1|' $FORKS
fi

REPO=$(grep "full_name" $FORKS | cut -f2 -d':' | sed 's/\"//g; s/\,//g; s/ //g' | dmenu -p "Select repository:" -l 20)
[ -z $REPO ] && exit
ANS1=$(printf "Yes\\nNo" | dmenu -p "Exit script and explore repository in browser?")
if [ $ANS1 = "Yes" ]; then
	$BROWSER https://github.com/$REPO
	exit
fi

notify-send "Downloading repository..." "This may take a moment"
git clone --depth 1 https://github.com/${REPO}.git ~/.cache/void-packages
PKG=$(ls ~/.cache/void-packages/srcpkgs | dmenu -p "Select package:" -l 20)
[ -z PKG ] && exit
cp -r ~/.cache/void-packages/srcpkgs/$PKG ${VPKG_PATH}/srcpkgs/
rm -rf ~/.cache/void-packages

cd $VPKG_PATH
git add srcpkgs/${PKG}
git commit -am "New package: ${PKG}"

ANS2=$(printf "Yes\\nNo" | dmenu -p "Build ${PKG}?")
if [ $ANS="Yes" ]; then
	notify-send "Building ${PKG}..." "This will likely take a while"
	./xbps-src pkg $PKG
	cd
else
	cd
	exit
fi
